### ISSUE TITLE
docker compose

### ISSUE THREAD

**Issue by atomotic** [dlcs/elucidate-server#91]
using the develop branch i'm able to start **elucidate** with the following `docker-compose.yml`
the liquibase migrations are working fine, as i can see tables created in the postgres container

would you like to include this in the documentation somewhere?
i'm walking through [USAGE.md](https://github.com/dlcs/elucidate-server/blob/master/USAGE.md) now to better understand the api

```
version: '3'
services:
  elucidate:
    image: 'dlcs/elucidate-server:1.4.3-SNAPSHOT'
    ports:
      - '8080:8080'
  database:
    image: 'postgres:10-alpine'
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=
     - POSTGRES_DB=annotations
```
